# TODO: recopier le code de l'application dans l'image
# - V0 : lancer un bash et vérifier que l'application est bien copiée

# - V1 : prevoir les variables d'environnement:
#    * DATABASE_URL à "sqlite:///./test.db"
#    * DDL_AUTO à "create"

# - v2 : installer les dépendances Python:
#   * pip install -r requirements.txt

# - v3 : lancer l'API
#   * uvicorn movieapi.main:app --host 0.0.0.0 --port 8000


