services:
  db:
    image: mariadb:${DB_TAG}
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
    volumes:
      - ${DB_SQL_INIT_DIR}:/docker-entrypoint-initdb.d
      - dbstorage:/var/lib/mysql
    ports:
      - ${DB_PORT:-3306}:3306

volumes:
  dbstorage:
    # NB: nom global
    name: ${DB_STORAGE}