services:
  db:
    image: mariadb:${DB_TAG}
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
    volumes:
      - ${DB_SQL_INIT_DIR}:/docker-entrypoint-initdb.d
      - dbstorage:/var/lib/mysql
    ports:
      - ${DB_PORT:-3306}:3306
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 3s
      interval: 10s
      timeout: 5s
      retries: 5

  admindb:
    image: adminer:${ADMINDB_TAG:-latest}
    depends_on: 
      - db
    restart: unless-stopped
    ports:
      - ${ADMINDB_PORT}:8080

  # api:
  #   TODO: api python

volumes:
  dbstorage:
    # NB: nom global
    name: ${DB_STORAGE}